name: UAT-DEPLOY-CI

run-name: ${{ github.actor }} 正在執行 ${{ github.workflow }} 工作流程： ${{ github.event.pull_request.title }}, ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - develop
    types: 
      - closed
  workflow_dispatch:

  
jobs:
  deploy:
    runs-on: self-hosted
    environment: uat-deploy
    env:
      BUILD_FOLDER: ${{ vars.BUILD_FOLDER }}
      S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://stackoverflow.com/questions/64226272/caching-npm-dependency-with-github-action
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: './node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Check Node.js & Yarn
      - name: Check Node.js & Yarn
        run: |
          node -v
          npm -v

      # run build script
      - name: Execute Build Script
        shell: bash
        run: |
          echo "Build Fontend"
          bash .github/scripts/develop/build.sh

      # Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./output/ s3://${{ vars.S3_BUCKET_NAME }} --delete --acl public-read --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      # Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      # Debug output folder
      - name: Debug output folder
        run: ls -R output